In [148]:
import numpy as np
import matplotlib.pyplot as plt
import struct
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.data as D

In [149]:
file = "CE1_BMYK_IIM_SCI_N_20081204060238_20081204081021_4457_A.2C"

In [150]:
file = "CE1_BMYK_IIM_SCI_N_20081204035456_20081204060237_4456_A.2C"

In [151]:
# import pds3

In [152]:
# lbl = PDS3Label(file)
# r = lbl['RECORD_LENGTH']
# shape = lbl['IMAGE']['LINES'], lbl['IMAGE']['LINE_SAMPLES']

In [153]:
try:
    File = open(file, 'rb')
except IOError:
    print("open error")
    File.close()

# f = File.read()
# offset=0
# fmt = '>cccc'
# test = struct.unpack_from(fmt, f, offset)
# test = f[2000:2500]


In [154]:
label = {
    'RECORD_BYTES':0,
    'FILE_RECORDS':0,
    'LABEL_RECORDS':0,
    '^IMAGE':0,
    '^IMAGE_PREFIX':0,
    '  ROWS':0,
    '  ROW_BYTES':0,
    '  LINES':0,
    }
while True:
# for i in range(10):
    line = File.readline()
    print(line)
    print(line.decode('utf8').replace('\t', ''))
    print(line.decode('utf8').replace('\t', '').split("="))

    lbl = line.decode('utf8').replace('\t', '').strip('\n').split("=")
    if lbl[0] == 'END':
        break
    if lbl[0] in label:
        label[lbl[0]] = int(lbl[1])

b'PDS_VERSION_ID\t\t\t=PDS3\n'
PDS_VERSION_ID=PDS3

['PDS_VERSION_ID', 'PDS3\n']
b'RECORD_TYPE\t\t\t=FIXED_LENGTH\n'
RECORD_TYPE=FIXED_LENGTH

['RECORD_TYPE', 'FIXED_LENGTH\n']
b'RECORD_BYTES\t\t\t=512\n'
RECORD_BYTES=512

['RECORD_BYTES', '512\n']
b'FILE_RECORDS\t\t\t=714621\n'
FILE_RECORDS=714621

['FILE_RECORDS', '714621\n']
b'LABEL_RECORDS\t\t\t=30\n'
LABEL_RECORDS=30

['LABEL_RECORDS', '30\n']
b'^IMAGE\t\t\t=2942\n'
^IMAGE=2942

['^IMAGE', '2942\n']
b'^IMAGE_PREFIX\t\t\t=31\n'
^IMAGE_PREFIX=31

['^IMAGE_PREFIX', '31\n']
b'DATA_SET_ID\t\t\t=\n'
DATA_SET_ID=

['DATA_SET_ID', '\n']
b'PRODUCT_NAME\t\t\t=Imaging Interferometer Science Data Product\n'
PRODUCT_NAME=Imaging Interferometer Science Data Product

['PRODUCT_NAME', 'Imaging Interferometer Science Data Product\n']
b'PRODUCT_ID\t\t\t=CE1_IIM_2C\n'
PRODUCT_ID=CE1_IIM_2C

['PRODUCT_ID', 'CE1_IIM_2C\n']
b'PUBLICATION_DATE\t\t\t=2008-12-06T03:21:47.000Z\n'
PUBLICATION_DATE=2008-12-06T03:21:47.000Z

['PUBLICATION_DATE', '2008-12-06T0

In [155]:
print(label)

{'RECORD_BYTES': 512, 'FILE_RECORDS': 714621, 'LABEL_RECORDS': 30, '^IMAGE': 2942, '^IMAGE_PREFIX': 31, '  ROWS': 2911, '  ROW_BYTES': 512, '  LINES': 22240}


In [156]:
skip = File.readline()
print(skip.decode('utf8'))

In [157]:
print(skip)

b'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [158]:
print(len(skip.decode('utf8')))

12888


In [159]:
inf = File.readline(67*label['  LINES'])

In [160]:
# print(inf[:100].decode('utf8'))
# print(inf[:100])


In [161]:
# print(inf[1490079:])

In [171]:
testinf = inf.decode('utf8').replace(' ', '').split("\t")
print(testinf[:100])
print(testinf[-100:])

# import re
 
# pattern = re.compile(r'([1-9]*-[1-9]*-[1-9]*T[1-9]*:[1-9]*:[1-9]*.[1-9]*Z\t0\t [1-9,-,.]*\t [1-9,-,.]*\t [1-9,-,.]*\t [1-9,-,.]*\t)')   # 查找数字
# result1 = pattern.findall(testinf)
# print(result1)

['2008-12-04T05:04:01.420Z', '0', '121.2097', '-77.4942', '124.8695', '-77.4382', '2008-12-04T05:04:01.586Z', '0', '121.2082', '-77.4862', '124.8657', '-77.4303', '2008-12-04T05:04:01.726Z', '0', '121.2069', '-77.4795', '124.8624', '-77.4236', '2008-12-04T05:04:01.866Z', '0', '121.2056', '-77.4728', '124.8592', '-77.4169', '2008-12-04T05:04:02.007Z', '0', '121.2044', '-77.4660', '124.8560', '-77.4101', '2008-12-04T05:04:02.147Z', '0', '121.2031', '-77.4593', '124.8528', '-77.4035', '2008-12-04T05:04:02.287Z', '0', '121.2018', '-77.4526', '124.8495', '-77.3968', '2008-12-04T05:04:02.427Z', '0', '121.2006', '-77.4459', '124.8464', '-77.3901', '2008-12-04T05:04:02.567Z', '0', '121.1993', '-77.4393', '124.8432', '-77.3835', '2008-12-04T05:04:02.707Z', '0', '121.1981', '-77.4326', '124.8400', '-77.3769', '2008-12-04T05:04:02.847Z', '0', '121.1969', '-77.4260', '124.8369', '-77.3703', '2008-12-04T05:04:02.988Z', '0', '121.1956', '-77.4193', '124.8337', '-77.3636', '2008-12-04T05:04:03.128Z',

In [172]:
pos = np.empty((label['  LINES'],4))
for i in range(label['  LINES']):
    for j in range(4):
        pos[i][j] = float(testinf[6*i + j + 2])
print(pos)

[[121.2097 -77.4942 124.8695 -77.4382]
 [121.2082 -77.4862 124.8657 -77.4303]
 [121.2069 -77.4795 124.8624 -77.4236]
 ...
 [114.7849  71.3126 117.4021  71.3515]
 [114.7834  71.3192 117.4016  71.3581]
 [114.782   71.3257 117.4011  71.3647]]


In [163]:
testF = '\t\t\t\t'
testB = testF.encode()
fmt = '>f'
test = struct.unpack_from(fmt, testB, offset = 0)
print(test)
print(len(f))

(1.6495023458867976e-33,)
365885952


In [164]:
# for i in range(22):
#     print(f[15360+i*1000*67:15360+i*1000*67 + 67])
# print(f[1505440:1505792])

In [165]:
# test = f[15360+0+28:15360+0+36]
# test = test.decode('utf-8')
# print(float(test))

In [166]:
# # test = f[1505792:1505800]
# # print(f[15360:15800])
# print(f[1505000:1505800])
# offset=struct.calcsize('>c')*1505792
# fmt = '>ff'
# test = struct.unpack_from(fmt, f, offset)
# print(test)
# print(len(f))



2008-12-04T07:12:01.668Z\t0\t 119.8104\t -76.7162\t 123.2579\t -76.6650\t

2008-12-04T07:12:01.809Z\t0\t 119.8094\t -76.7096\t 123.2551\t -76.6583\t

2008-12-04T07:12:01.949Z\t0\t 119.8083\t -76.7029\t 123.2523\t -76.6517\t

2008-12-04T07:12:02.089Z\t0\t 119.8072\t -76.6963\t 123.2495\t -76.6451\t

2008-12-04T07:12:02.229Z\t0\t 119.8062\t -76.6897\t 123.2467\t -76.6385\t

2008-12-04T07:12:02.369Z\t0\t 119.8051\t -76.6830\t 123.2440\t -76.6319\t

end

2008-12-04T08:03:57.945Z\t0\t 113.5178\t  72.0728\t 116.2450\t  72.1125\t

2008-12-04T08:03:58.085Z\t0\t 113.5162\t  72.0795\t 116.2445\t  72.1191\t

2008-12-04T08:03:58.226Z\t0\t 113.5146\t  72.0862\t 116.2439\t  72.1258\t

2008-12-04T08:03:58.366Z\t0\t 113.5131\t  72.0928\t 116.2434\t  72.1324\t

2008-12-04T08:03:58.506Z\t0\t 113.5115\t  72.0994\t 116.2429\t  72.1390\t

2008-12-04T08:03:58.646Z\t0\t 113.5100\t  72.1059\t 116.2423\t  72.1456\t

2008-12-04T08:03:58.786Z\t0\t 113.5084\t  72.1125\t 116.2418\t  72.1522\t

2008-12-04T08:03:58.926Z\t0\t 113.5069\t  72.1190\t 116.2412\t  72.1587\t

In [167]:
File.close()


In [168]:
def loadData(file):
    try:
        F = open(file, 'rb')
    except IOError:
        print("open error")
        F.close()

    f = F.read()

    offset=0
    fmt = '>iiii'
    magic, images, rows, columns = struct.unpack_from(fmt, f, offset)

    offset += struct.calcsize(fmt)
    fmt = '>' + str(rows * columns) + 'B'

    # images = 10 # for test

    # for CNN
    ImageSet = np.empty((images, 1, rows, columns))
    for i in range(images):
        ImageSet[i] = np.array(struct.unpack_from(fmt, f, offset)).reshape((1, rows, columns))
        offset += struct.calcsize(fmt)